a = float(input("Enter first number: "))
b = float(input("Enter second number: "))
addition = a + b
subtraction = a - b
multipliction = a * b
division = b / a
print("Addition =", addition)
print("Subtraction =", subtraction)
print("multipliction =", multipliction)
print("division =", division)
